import turtle
turtle.home()

turtle.circle(100)
turtle.penup()
turtle.left(90)
turtle.forward(50)
turtle.right(45)
turtle.forward(50)
turtle.right(180)
turtle.pendown()
turtle.forward(50)
turtle.right(90)
turtle.forward(50)
turtle.penup()
turtle.home()
turtle.forward(50)
turtle.left(90)
turtle.forward(140)
turtle.pendown()
turtle.circle(10)
turtle.penup()
turtle.left(90)
turtle.forward(95)
turtle.right(90)
turtle.pendown()
turtle.circle(10)

input("press enter to exit")
